name: Check
on:
  pull_request:
  workflow_call:
jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Check build
        run: pnpm run build:check
  format:
    name: Format
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Check format
        run: pnpm run format:check
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Check lint
        run: pnpm run lint:check
