name: Check
on:
  pull_request:
  workflow_call:
jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Check format
        run: pnpm run format:check
